language: php

dist: precise

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=Pas
    - REQUIRE=""
    - DB=mysql CAKE_REF=2.4.0

  matrix:
    - DB=mysql CAKE_REF=2.4.0
    - DB=mysql CAKE_REF=2.5.0
    - DB=mysql CAKE_REF=2.6.0

matrix:
  include:
    - php: 5.4
      env:
        - CODECOVERAGE=1
    - php: 5.4
      env:
        - PHPCS=1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
